# Generated by Django 5.2.1 on 2025-06-01 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('summary', models.TextField(max_length=2000)),
                ('pages', models.CharField(max_length=80)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('author', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('author_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='man.png', upload_to='media/')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OTPforRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('max_otp_try', models.CharField(default=3, max_length=2)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='bookapp.user')),
            ],
        ),
    ]
