# Generated by Django 5.2.1 on 2025-06-02 18:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('author', 'Author'), ('reader', 'Reader')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('summary', models.TextField(max_length=2000)),
                ('pages', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=80)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookapp.appuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.RemoveField(
            model_name='otpforregistration',
            name='otp_max_out',
        ),
        migrations.AlterField(
            model_name='otpforregistration',
            name='max_otp_try',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='otpforregistration',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpforregistration',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 18, 16, 3, 159566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otpforregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.appuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
