# Generated by Django 5.2.1 on 2025-06-02 18:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_appuser_book_delete_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpforregistration',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 18, 35, 14, 223667, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otpforregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookapp.appuser'),
        ),
    ]
