# Generated by Django 5.2.1 on 2025-06-03 04:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_otpforregistration_otp_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summary',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book-cover/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book-pdf/'),
        ),
        migrations.AlterField(
            model_name='otpforregistration',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 4, 57, 4, 518862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UsersBooks',
            fields=[
                ('userbook', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='bookapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_books', to='bookapp.appuser')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
